src/c/vensim.c
src/c/vensim.h

More details in #22.  In short, most wrapper functions in `vensim.c` have been replaced by macros defined in `vensim.h`.  There are some wrapper functions that I left unchanged where a macro implementation would be too complex or wouldn't provide a performance improvement.  For example, `_XIDZ` and `_ZIDZ` reference the `b` parameter twice which in macro form could lead to double evaluation.
Fixes #22

perf: replace vensim wrapper functions with macros

---

src/c/vensim.c

More details in #24.  The goal here is to minimize the number of instructions, since this function is on the hot path.  On each iteration, we do less book keeping for the index, and we now only access the x value; the y value is only needed if it's a match.  Previously we would do two comparisons per iteration (`feq` and `fgt`, i.e., equal and greater-than), whereas now we only need a single comparison (`fge`, i.e., greater-than-or-equal).
Fixes #24

perf: optimize __lookup function

---

.github/workflows/build.yaml
models/delay/delay.dat
models/delay/delay.mdl
src/tests/modeltests

build: add workflow for building and testing on GitHub Actions

---

src/c/vensim.c
src/c/vensim.h

perf: cache last input and last accessed index for faster lookups

---

src/CodeGen.js
src/c/model.c
src/c/sde.h

feat: add `runModelWithBuffers` entry point that takes pre-allocated input/output buffers

---

README.md
package-lock.json
package.json
src/sde-generate.js

This change removes 135 transitive dependencies by making `browserify` an optional install.
Fixes #52

fix: make browserify an optional dependency

---

models/preprocess/expected.mdl
models/preprocess/input.mdl
models/preprocess/preprocess_check.sh
src/Preprocessor.js
src/tests/modeltests

This fixes the case insensitivity part of the previous commit, and improves upon it by also removing trailing whitespace and fixing the placement of the comment marker so that the markers are consistent for all declarations.
I've also added a test that checks that the output of the preprocessor matches a reference mdl file.
Fixes #55

fix: use case-insensitive sort and remove trailing whitespace in preprocessor

---

src/Model.js

More details in the issue comments (#62).
In summary, running `sde generate --genc` for the En-ROADS model used to take 2 minutes 2 seconds on my laptop, and with these changes, it now takes under 5 seconds.
Fixes #62

perf: improve code gen performance by avoiding linear searches

---

models/comments/comments.dat
models/comments/comments.mdl
models/comments/comments_check.sh
models/comments/comments_vars.txt
models/comments/expected.mdl
src/Helpers.js
src/Preprocessor.js

Fixes #73 
This PR changes the preprocessor to remove inline comments from the model before parsing it. A test model is included that illustrates several use cases. A special string scanner function was required because a regular expression could not cover all cases. A regexp would need to be greedy to match the case with nested comments, but cannot be greedy to match the case with two comments in one string.

feat: remove inline comments in the preprocessor

---

models/delay/delay_vars.txt
src/EquationGen.js
src/EquationReader.js

Fixes #91 
The delay test generated NaN values for aux vars subscripted with a subdimension. Aux vars are generated as part of internal delay equation generation. They are added in the analysis stage after the model vars have already been read. The problem was that vars on a subdimension must be separated into individually indexed vars, and this was not being done for the generated aux vars. There is a mechanism to add "non a-to-a" (separated vars in XMILE terminology) after the initial scan of model variables. This was used to add separated aux vars and get the correct refid for references. The DELAY1 and DELAY3 functions both needed this change in somewhat different variations. I regenerated the variable listing too to account for the new aux vars. The delay test now passes without the …

fix: use correct subdimension index for delay aux vars

---

src/Helpers.js

Removed the try/catch block as agreed.
This is an additional fix for #81 as discussed in PR #82; will be merged into the `todd/81-direct-data-csv` branch.
Chris edit: I'm pasting the additional context from [Todd's comment](https://github.com/climateinteractive/SDEverywhere/pull/82#issuecomment-887027179) from #82:
> I removed the try/catch block around the CSV parse. I tested it with a bad pathname and got the following unhandled exception error message:
```
Error: ENOENT: no such file or directory, open '/Users/toddfincannon/Projects/SDEverywhere/models/directdata/x_data.csv'
```
>  think this is clear enough that we don't need a special error message.

fix: allow CSV read exception to propagate instead of catching it

---

package-lock.json
package.json
src/EquationReader.js

Fixes #119 
This change is required when using antlr4-vensim#7911c04 (see related issue https://github.com/climateinteractive/antlr4-vensim/issues/7). I branched from develop so it can be merged immediately test test the antlr4-vensim change.

fix: terminate generated equations with ~~|

---

src/EquationGen.js
src/c/vensim.c
src/c/vensim.h

Fixes #159 
I made one other change in `vensim.c` to make it possible to compile with gcc, which does not support UTF-8 source files like clang does. I had used clever μ and σ variable names in probability-related code. I replaced these with `mu` and `sigma` and SDEverywhere C code compiled with gcc just fine.

fix: prevent memory leaks in fixed delay initialization

---

packages/check-core/src/perf/perf-stats.ts
packages/check-core/src/suite/suite-runner.spec.ts
packages/check-core/src/suite/suite-runner.ts

fix: make runSuite proceed to completion when no checks are defined

---

packages/plugin-check/src/vite-config-for-report.ts

fix: configure cacheDir in Vite config for plugin-check report

---

packages/plugin-check/src/vite-config-for-report.ts

fix: add explicit "optimizeDeps.include" entries for check report Vite config

---

.github/workflows/build.yaml
packages/build/src/build/impl/gen-model.ts
packages/build/src/config/config-loader.ts
packages/cli/package.json
packages/cli/src/main.js
packages/cli/src/sde-bundle.js
packages/cli/src/sde-compile.js
packages/cli/src/sde-dev.js
packages/cli/src/sde-which.js
packages/cli/src/utils.js
packages/plugin-check/src/plugin.ts
packages/plugin-check/src/vite-config-for-tests.ts
pnpm-lock.yaml
scripts/ci-build
tests/modeltests

Fixes #222 
See issue for more details.

fix: correct handling of paths on Windows and those containing spaces

---

packages/plugin-check/src/vite-config-for-report.ts

fix: exclude moment dependency in plugin-check report config

---

examples/hello-world/.gitignore
examples/hello-world/package.json
examples/sample-check-app/src/index.ts
examples/template-default/.gitignore
examples/template-default/package.json
examples/template-minimal/.gitignore
examples/template-minimal/package.json
packages/check-ui-shell/src/_shared/stores.ts
packages/check-ui-shell/src/app-init.ts
packages/check-ui-shell/src/app.svelte
packages/check-ui-shell/src/components/check/summary/check-summary-row-vm.ts
packages/check-ui-shell/src/components/check/summary/check-summary-test-vm.ts
packages/check-ui-shell/src/components/header/header-vm.ts
packages/check-ui-shell/src/components/header/header.pug
packages/check-ui-shell/src/components/header/header.svelte
packages/check-ui-shell/src/components/stats/stats-table-vm.ts
packages/check-ui-shell/src/global.css
packages/check-ui-shell/types/index.d.ts
packages/plugin-check/bin/sde-check.js
packages/plugin-check/package.json
packages/plugin-check/src/plugin.ts
packages/plugin-check/src/vite-config-for-bundle.ts
packages/plugin-check/src/vite-config-for-report.ts
packages/plugin-check/template-bundle/src/bundle.ts
packages/plugin-check/template-bundle/src/empty-model-spec.ts
packages/plugin-check/template-report/index.html
packages/plugin-check/template-report/src/env.d.ts
packages/plugin-check/template-report/src/index.ts
pnpm-lock.yaml

Fixes #244 
This improves the `check-ui-shell` package and the model-check report template used by `plugin-check` so that it is now possible for the user to save a baseline bundle and select from a list of available bundles in the report header.  See screenshot below.
The `plugin-check` package now exposes an `sde-check` cli tool that currently only contains one command:
```
sde-check baseline --save
```
This will copy the current `sde-prep/check-bundle.js` file to the `baselines` directory and rename it to include a timestamp.
The report created by `plugin-check` will refresh automatically when bundles are added/removed, and the report will also update when the user chooses a new "baseline" or "current" bundle.
As part of this PR, I also made a few usability improvements in the …

feat: allow for selecting different model-check baseline bundle in local dev mode

---

examples/template-default/packages/app/index.html

Fixes #236 
This changes the hardcoded "SIR" that I accidentally left in place when I migrated the old sir app to become the new `template-default`; it now uses the generic "Model Explorer" as the title.

fix: replace hardcoded title in app template

---

packages/cli/src/c/model.c

Fixes #253 
A test that verifies this will be added soon as part of a small integration test that uses the runtime and runtime-async packages.

fix: initialize numSavePoints after evalAux to get correct SAVEPER value

---

packages/plugin-vite/package.json
pnpm-lock.yaml

Fixes #268 
Simple fix to make vite a peer dependency instead of hard dependency for plugin-vite.

fix: make vite a peer dependency for plugin-vite

---

.github/workflows/build.yaml
.github/workflows/release.yaml

Fixes #270 
This also upgrades various actions used in the workflows to the latest versions that include fixes for set-outputs and Node 12 -> 16.
With these changes in place, we no longer have any deprecation warnings in the build logs.

build: use GITHUB_OUTPUT as replacement for set-output

---

packages/check-ui-shell/src/components/graphs/comparison-graph-view.ts

fix: make colors for comparison graph plots match dataset styles

---

.github/workflows/build.yaml
.gitignore
scripts/ci-run-c-int-tests
scripts/ci-run-js-int-tests
scripts/install-emsdk
tests/run-js-int-tests

Fixes #275 
This makes the necessary changes to the GitHub Actions `build` workflow to have separate jobs for the C-level and JS-level integration tests.  The new `test_js` installs the Emscripten SDK, which is required for building the wasm models used by the JS-level tests.
I didn't hook it up to an actual test in this PR, but the first one is arriving shortly with the `SAVEPER` fixes.

build: add separate job to build workflow for running JS-level integration tests

---

packages/cli/src/c/model.c
packages/cli/src/c/sde.h
packages/compile/src/generate/code-gen.js
pnpm-lock.yaml
tests/integration/ext-control-params/.gitignore
tests/integration/ext-control-params/ext-control-params.csv
tests/integration/ext-control-params/ext-control-params.mdl
tests/integration/ext-control-params/package.json
tests/integration/ext-control-params/run-tests.js
tests/integration/ext-control-params/sde.config.js
tests/run-js-int-tests

Fixes #301 
With this change we no longer generate the control param accessors as part of code gen, but instead define accessors in `model.c` that return the computed values (e.g., `_initial_time`).  For this to work correctly in cases where the model's control parameters are computed (or initialized based on external data files), we run the model for the first time step only, and we do this lazily on first use of the accessors.
No change in behavior for models that use constant values for the control params.  This fix mainly applies to models that define the control params in an external file, like EPS.
I added a JS-level integration test that verifies the behavior for the latter case where they are defined in an external csv file.  For this test, we actually cover a mix of external and …

fix: initialize control parameters prior to access

---

packages/build/docs/interfaces/InputSpec.md
packages/build/src/_shared/model-spec.ts
packages/plugin-config/src/context.ts
packages/plugin-config/src/gen-inputs.ts
packages/plugin-config/src/processor.spec.ts

Fixes #320 
Technically this should be a `feat` commit but since it's an optional property I will stick with `fix` so that it's a semver patch bump and less disruptive for packages that have a peer dependency on the `build` package.

fix: add inputId property to InputSpec interface

---

.github/workflows/build.yaml
.github/workflows/release.yaml
pnpm-lock.yaml

Fixes #339 
This updates the lock file to use the latest file format from pnpm 8, and also updates the GitHub Actions workflows to use pnpm 8 instead of 7.
This has no impact on which dependencies we use, nor does it impact how we install dependencies.

build: upgrade to pnpm 8

---

examples/sample-check-app/package.json
examples/sample-check-app/svelte.config.js
examples/template-default/packages/core/tsconfig.json
package.json
packages/build/package.json
packages/build/tsup.config.ts
packages/check-ui-shell/package.json
packages/check-ui-shell/svelte.config.js
packages/create/.prettierignore
packages/create/package.json
packages/create/tests/step-directory.spec.ts
packages/plugin-check/package.json
packages/plugin-check/template-bundle/tsconfig.json
packages/plugin-check/template-report/tsconfig.json
packages/plugin-check/template-tests/tsconfig.json
packages/plugin-check/tsup.config.ts
packages/plugin-config/package.json
packages/plugin-config/tsup.config.ts
packages/plugin-wasm/package.json
packages/plugin-worker/package.json
packages/plugin-worker/tsup.config.ts
packages/runtime/docs/classes/ModelScheduler.md
packages/runtime/docs/classes/Outputs.md
packages/runtime/docs/classes/WasmModel.md
pnpm-lock.yaml
tsconfig-common.json

Fixes #345 
This upgrades TypeScript, Svelte, and other related packages as described in the issue.  This has no visible impact on the development side (other than it helps resolve some warnings that are raised in VS Code due to the deprecation mentioned in the issue).  And there's no significant impact on the packages that will eventually be published, which is why I'm using the `build` type and not `fix` (no need to publish packages right away).

build: upgrade to typescript 5.x + most recent svelte 3.x + other related packages

---

scripts/ci-build

Fixes #347 
More details in the issue.  There's no change in what build steps we perform; only changes the order in which things are built.  I will merge this shortly.
To summarize the perf gains:
| machine | before | after |
| -- | --: | --: |
| M1 Max (10 cores) | 1m45s | 29s |
| GitHub Actions (2 cores) | 4m40s | 2m51s |
/cc @ToddFincannonEI

build: reduce build time by running more steps in parallel

---

scripts/ci-run-js-int-tests
tests/run-js-int-tests

Fixes #347
This follows on the earlier PR #348 to apply similar changes to the `ci-run-js-int-tests` script.  See issue for more details.

build: reduce js integration test time by running more steps in parallel

---

packages/cli/src/sde-compare.js
packages/cli/src/sde-log.js
packages/cli/src/utils.js
packages/compile/src/_shared/helpers.js
packages/compile/src/_shared/read-dat.js
packages/compile/src/_shared/subscript.js
packages/compile/src/generate/code-gen.js
packages/compile/src/generate/equation-gen.js
packages/compile/src/generate/model-lhs-reader.js
packages/compile/src/model/equation-reader.js
packages/compile/src/model/model.js
packages/compile/src/model/subscript-range-reader.js
packages/compile/src/model/var-name-reader.js
packages/compile/src/model/variable-reader.js
packages/compile/src/preprocess/preprocessor.js

Fixes #349 
@ToddFincannonEI: See issue for more details.  No impact on `sde` behavior but needed to unblock testing via vitest.

fix: change ramda imports to wildcard style

---

examples/hello-world/package.json
examples/sample-check-app/package.json
examples/sample-check-bundle/package.json
examples/sample-check-tests/package.json
examples/template-default/packages/app/package.json
examples/template-default/packages/core/package.json
package.json
packages/check-ui-shell/package.json
packages/plugin-check/package.json
packages/plugin-check/src/vite-config-for-bundle.ts
packages/plugin-check/src/vite-config-for-report.ts
packages/plugin-check/src/vite-config-for-tests.ts
packages/plugin-check/template-report/src/env.d.ts
packages/plugin-check/template-report/src/index.ts
packages/plugin-check/template-tests/src/env.d.ts
packages/plugin-check/template-tests/src/index.ts
packages/plugin-vite/docs/interfaces/VitePluginOptions.md
packages/plugin-vite/package.json
packages/plugin-worker/package.json
packages/plugin-worker/src/vite-config.ts
pnpm-lock.yaml

Fixes #351 
This upgrades all uses of vite from 3.x (3.1.3) to the most recent 4.x (4.4.9).  See issue for more details.
All automated tests are passing, and I also tested the hello-world sample in isolation with pnpm, npm, and yarn and all seems OK.  I'll test again after I publish the new packages.

fix: upgrade to vite 4.4.9

---

packages/plugin-config/CHANGELOG.md
packages/plugin-vite/CHANGELOG.md
packages/runtime/CHANGELOG.md

Fixes #361 
No behavior changes, just going through the motions to hopefully get `npm publish` to work the next time.

fix: add trivial changes to correct previous publish failures and force re-publish

---

examples/template-default/packages/core/src/model/model.ts

Fixes #366 
Simple fix to the default template.

fix: use import type when importing Input in default template

---

examples/hello-world/README.md
examples/hello-world/package.json
examples/template-default/package.json
examples/template-default/packages/app/package.json
examples/template-default/packages/core/package.json
examples/template-minimal/package.json
pnpm-lock.yaml

Fixes #272 
This is a minor change to the example apps and the templates used by the `create` package.  No impact on published packages.
The removal of `sirv-cli` helps reduce the number of overall dev dependencies for the SDE repo.

build: use vite preview in examples + update SDE dependencies in templates

---

packages/plugin-wasm/docs/interfaces/WasmPluginOptions.md
packages/plugin-wasm/src/options.ts
packages/plugin-wasm/src/plugin.ts

Fixes #371 
This adds the ability to override the default arguments that are passed to the `emcc` command in plugin-wasm.
I also made it so that `emsdkDir` and `emccArgs` accept a `() => string` as an alternative to a plain string.  This makes it easier to experiment with arguments (by reading them from a file, for example) while dev mode remains running.

feat: allow for customizing emcc arguments in plugin-wasm

---

packages/build/package.json

This is an attempt to address the sporadic test failures that started occurring in the build package tests this week.  I'm not sure of the underlying cause or why it started happening suddenly, but running sequentially with a higher timeout seems to help so far.

build: use --threads=false and increase default timeout for build package tests

---

.github/workflows/build.yaml

When Travis submitted a PR a couple weeks ago from an external fork, I added a temporary fix to the `build.yaml` workflow so that it runs for both `push` and `pull_request` events, but this leads to redundant builds in the more typical case where the workflow is run for a branch of the primary SDEverywhere repo.
I'm attempting to address this by skipping jobs in the case where it's a `pull_request` event for a branch of this repo.  We'll see if it works after I open this PR.

build: only run build workflow for push events OR pull_request events from fork

---

models/directconst/directconst.mdl
models/directdata/directdata.mdl
models/directlookups/directlookups.mdl
models/directsubs/directsubs.mdl
packages/compile/src/generate/equation-gen.js
packages/compile/src/generate/gen-equation-c.spec.ts
packages/compile/src/model/read-equations.spec.ts
packages/compile/src/model/read-variables.spec.ts
packages/compile/src/model/subscript-range-reader.js

Fixes #395 
This is a simple fix that allows `GET DIRECT ...` calls to use a cell reference that has lowercase letters instead of the more typical uppercase ones.  Vensim is lenient and allows either form, but the XLSX library we use in SDE is not lenient, so I've added a `toUpperCase()` call in the appropriate places.
I also added some error handling so that users will get a more useful error message in the unlikely case where an invalid cell reference is used (instead of allowing things to pass through).
I updated the existing integration tests and also added some new unit tests to verify this.

fix: allow lowercase cell reference in GET DIRECT function calls

---

packages/compile/src/generate/equation-gen.js
packages/compile/src/generate/gen-equation-c.spec.ts
packages/compile/src/model/read-equations.spec.ts

Fixes #403
This improves the code gen tests to cover more cases that I found while working on the new parsing/reading code in the separate `chris/parse` branch.  All tests are passing with both the existing implementation and the new one on that branch.
I included one tiny fix in this PR to remove a harmless but redundant semicolon in one case of a lookup definition.  I removed the extra semicolon so that the tests (expecting a single semicolon) pass for both old and new implementations.

test: expand code gen test coverage for trig functions, lookups, const lists, and subscripts

---

packages/parse/src/ast/reduce-expr.spec.ts
packages/parse/src/ast/reduce-expr.ts

Fixes #408 
Small fix (with test included) for an issue I found in the new `parse` package when testing with En-ROADS.  More details in the issue.

fix: change reduceConditionals to not resolve variable references outside of the condition expression

---

packages/parse/src/ast/ast-builders.ts
packages/parse/src/ast/ast-types.ts
packages/parse/src/vensim/parse-vensim-model.spec.ts
packages/parse/src/vensim/parse-vensim-model.ts
packages/parse/src/vensim/preprocess-vensim.spec.ts
packages/parse/src/vensim/preprocess-vensim.ts

Fixes #417
This is a low-risk change in the new `parse` package and tests are passing, so I will merge it shortly.  The group names are not useful in the `compile` package at this time, so they will be ignored at that level, but they are helpful for an internal tool I'm working on.

feat: preserve Vensim group names during preprocessing and parsing

---

packages/build/src/build/impl/gen-model.ts
packages/cli/src/sde-causes.js
packages/cli/src/sde-generate.js
packages/cli/src/sde-names.js
packages/compile/src/generate/code-gen.js
packages/compile/src/parse-and-generate.js
packages/create/src/step-config.ts

Fixes #424
See issue for more details.  This helps improve build performance by quite a bit when using the `sde bundle` or `sde dev` commands.

fix: allow `--genc` and `--list` arguments to be used in the same `sde generate` command

---

.github/workflows/build.yaml
.github/workflows/release.yaml
README.md

Fixes #427 
This updates the GitHub Actions workflows to use newer versions of actions that run on Node 20 to resolve deprecation warnings.
This does not update the version of Node that we use to build and test SDE.  I will be filing a separate issue to address that shortly.

build: update actions in workflows to use Node 20

---

.github/workflows/build.yaml
.github/workflows/release.yaml
README.md
packages/cli/package.json

Fixes #431 
See issue for more details.  This updates the docs and build workflows to use Node v18 as minimum supported version.  I also added `engines` to the `package.json` for the cli package.  (This is more advisory; it only produces a warning if the current node version is < 18, unless `engine-strict` config is enabled.)

fix: require Node.js v18 as minimum supported version

---

packages/build/src/build/build.ts
packages/build/src/build/impl/build-once.ts
packages/build/src/build/impl/gen-model.ts
packages/build/tests/_shared/submodel1.mdl
packages/build/tests/_shared/submodel2.mdl
packages/build/tests/build/build-prod.spec.ts
packages/cli/src/sde-bundle.js
packages/cli/src/sde-dev.js
packages/cli/src/sde-generate.js
packages/compile/src/_shared/helpers.js
packages/compile/src/_shared/read-dat.js
packages/compile/src/_shared/read-dat.spec.ts
packages/compile/src/generate/code-gen.js
packages/compile/src/generate/gen-code-c.spec.ts
packages/compile/src/model/model.js
packages/compile/src/model/toposort.js
packages/plugin-wasm/src/plugin.ts

Fixes #260 
@ToddFincannonEI: The gory details are in the issue, but TL;DR this improves error handling in a number of areas to:
1. add error handling in places where we didn't have it quite right (like in `readDat`) and
2. avoid `process.exit` and instead allow errors to bubble up and get reported in a standard way

fix: improve error handling/reporting and prevent premature exit in dev mode

---

packages/compile/src/generate/gen-code-c.spec.ts
packages/compile/src/generate/gen-equation-c.spec.ts
packages/compile/src/model/model.js

Fixes #438 
@ToddFincannonEI: Here's a fix for an issue that a newcomer to SDE encountered today.  It's kind of an edge case that doesn't matter much once you get a project up and running, but can be a source of confusion when starting a new project.  See issue for more details.
Here's the diff with expanded scope to make it easier to see that the only change is to apply the same handling for input variables that we use for output variables (chop off the subscript part):

fix: prevent subscripted input variables from being pruned

---

examples/sample-check-bundle/src/graphs.ts
examples/sample-check-tests/src/comparisons/comparisons.yaml
packages/check-ui-shell/src/components/graphs/context-graph-vm.ts
packages/check-ui-shell/src/components/graphs/context-graph.svelte

Fixes #450 
This improves model-check to prevent a (previously unhandled) error in the case where a scenario is not available in one or both sides.
The main fix here is in `ContextGraphViewModel`: we shouldn't be calling `getGraphLinksForScenario` in the case where the scenario is undefined for that side.  In other similar cases where we call back into the bundle, we handled the undefined scenario case, but this case was overlooked.  In general, we should never be calling back into the bundle in the case where the scenario is undefined.
As a related improvement, I changed the view to have different messages for the two cases (graph not available vs scenario not available or invalid).
I also updated the sample-check-* packages to exercise these cases.

fix: correct handling of the case where comparison scenario is not valid for one side

---

examples/sample-check-tests/src/comparisons/comparison-specs.ts
examples/sample-check-tests/src/comparisons/comparisons.yaml
packages/check-core/src/comparison/config/_mocks/mock-spec-types.ts
packages/check-core/src/comparison/config/comparison-spec-types.ts
packages/check-core/src/comparison/config/resolve/comparison-resolver.spec.ts
packages/check-core/src/comparison/config/resolve/comparison-resolver.ts
packages/check-core/src/comparison/config/resolve/comparison-scenario-specs.ts

Fixes #453 
This makes it possible to define a comparison scenario that involves a set of inputs for the "left" model that is different from the set of inputs for the "right" model.  See issue for more details.

feat: add support for comparison scenarios that have different input settings in the two models

---

packages/create/package.json
packages/create/src/step-git.ts
packages/create/src/step-template.ts
pnpm-lock.yaml

Fixes #464 
This updates the `create` package so that it works even if Git is not installed locally.  Also improved the error messages.  See issue for more details.

fix: replace degit with giget so that `create` package doesn't depend on Git being installed locally

---

packages/plugin-wasm/docs/interfaces/WasmPluginOptions.md
packages/plugin-wasm/src/options.ts
packages/plugin-wasm/src/plugin.ts
packages/runtime/README.md

Fixes #474 
This adds `_free` to the list of functions that are expected by the runtime.  It was already declared in `WasmModule` and used in the implementation of `WasmBuffer.dispose`, but the latter isn't currently called (though it soon will be), so it's important that we update plugin-wasm and its documentation to correct this oversight.

fix: update plugin-wasm to export `_free` function

---

packages/plugin-wasm/src/plugin.ts
packages/plugin-wasm/src/var-names.ts
tests/integration/impl-var-access/run-tests.js

Fixes #481 
See issue for more details.  This change doesn't affect compatibility of the generated Wasm module.  The `outputVarIds` array will be put to use soon in another branch under development.

fix: change plugin-wasm to expose outputVarIds in the generated module

---

examples/house-game/sde.config.js
packages/build/.gitignore
packages/build/docs/interfaces/ResolvedConfig.md
packages/build/docs/interfaces/UserConfig.md
packages/build/src/_shared/resolved-config.ts
packages/build/src/build/impl/gen-model.ts
packages/build/src/config/config-loader.ts
packages/build/src/config/user-config.ts
packages/build/tests/build-dev/build-dev.spec.ts
packages/build/tests/build-prod/build-prod.spec.ts
packages/build/tests/config/config.spec.ts

Fixes #492 
This adds a new optional `outListingFile` property to `UserConfig` (as used in `sde.config.js`), which simplifies the process of copying the model listing file to a specific location, like a source code directory.
The one place where this was relevant was the new `house-game` example.  I was able to simplify the `sde.config.js` file for that project to use this new property instead of the old workaround, which was a custom plugin that copied the file.
As part of this, I updated the `build` package tests to remove the `sde-prep` directory between runs, and moved the `build-dev` and `build-prod` tests into separate directories, since before there was a chance that they would share the same `sde-prep` directory, which could lead to race conditions.

feat: add optional `outListingFile` config property that copies model listing JSON file as post-generate step

---

packages/runtime-async/tests/runner.spec.ts
packages/runtime/src/js-model/js-model.ts
packages/runtime/src/model-runner/synchronous-model-runner.spec.ts
packages/runtime/src/runnable-model/base-runnable-model.ts
packages/runtime/src/runnable-model/buffered-run-model-params.spec.ts
packages/runtime/src/runnable-model/buffered-run-model-params.ts
packages/runtime/src/runnable-model/referenced-run-model-params.spec.ts
packages/runtime/src/wasm-model/_mocks/mock-wasm-module.ts
packages/runtime/src/wasm-model/wasm-model.ts

Fixes #498 
More details in the issue.  Most of the changes were in tests and mocks to verify the small fixes.

fix: allow runModel to proceed without error when inputs array is empty

---

packages/cli/src/c/model.c
packages/cli/src/c/sde.h
packages/compile/src/generate/gen-code-c.js
packages/compile/src/generate/gen-code-c.spec.ts
packages/runtime/src/_shared/types.ts
packages/runtime/src/_shared/var-indices.spec.ts
packages/runtime/src/_shared/var-indices.ts
packages/runtime/src/js-model/js-model.ts
packages/runtime/src/model-runner/synchronous-model-runner.spec.ts
packages/runtime/src/runnable-model/buffered-run-model-params.spec.ts
packages/runtime/src/runnable-model/buffered-run-model-params.ts
packages/runtime/src/runnable-model/referenced-run-model-params.spec.ts
packages/runtime/src/runnable-model/referenced-run-model-params.ts

Fixes #506 
This is a refactoring that has no impact on existing projects; it just cleans up the way some values are encoded internally in the runtime and removes restrictions on the number of subscripts that can be used by a variable in some less commonly used cases (when overriding lookups or accessing impl variables at runtime).  See issue for more details.

fix: change encoding of variable and lookup indices to allow for arbitrary number of subscripts

---

examples/house-game/package.json
examples/house-game/packages/app/.eslintignore
examples/house-game/packages/app/.eslintrc.cjs
examples/house-game/packages/app/.prettierignore
examples/house-game/packages/app/package.json
examples/house-game/packages/app/src/app-vm.ts
examples/house-game/packages/app/src/components/assumptions/assumptions-vm.ts
examples/house-game/packages/app/src/model/app-model.ts
scripts/ci-build

Fixes #508 
This fixes the `ci-build` script, which wasn't previously building the house-game and hello-world examples (accidental oversight).  This uncovered an incorrect path in the eslint config file for the house-game project.  Once that was fixed, it uncovered some minor lint warnings in the house-game project, which I fixed here as well.

build: update ci-build script so that it includes all available example packages

---

packages/create/src/index.ts
packages/create/src/step-config.ts

Fixes #510 
This addresses an issue with the `create` package (used in the Quick Start instructions).  See issue for more details.  I'll merge this and will publish the fixed `create` package shortly.

fix: include new columns in generated model.csv file

---

packages/runtime/src/index.spec.ts
packages/runtime/src/index.ts

Fixes #514 
This restores the exports for two perf-related functions that aren't technically part of the public API for the `runtime` package, but are used in some of our internal tools.

fix: restore exports of non-public perf functions in runtime package

---

packages/runtime/src/runnable-model/buffered-run-model-params.spec.ts
packages/runtime/src/runnable-model/buffered-run-model-params.ts
packages/runtime/src/runnable-model/referenced-run-model-params.spec.ts
tests/integration/impl-var-access/run-tests.js
tests/integration/impl-var-access/sde.config.js

Fixes #524 
See issue for more details.  I added new unit tests to verify this case (for both `RunModelParams` implementations) and also updated the existing `impl-var-access` integration test so that it verifies this case as well (previously it used the same number of outputs in two different runs, so the bug was masked, but now it is covered better).

fix: prevent error when model outputs buffer is larger than the RunModelParams internal buffer

---

packages/compile/src/model/model.js
packages/compile/src/model/model.spec.ts

Fixes #527 
This fixes a regression in the JSON listing generated by `sde generate --list`, where `initial` variables were not being included like they used to.  I updated the existing unit test to improve coverage of this case.

fix: include 'initial' variables in JSON model listing

---

packages/compile/src/model/model.js

Fixes #528 
Small optimization that has no impact on behavior.  See issue for more details.

fix: cache sorted variables to improve compile performance

---

package.json
packages/parse/package.json
pnpm-lock.yaml
tests/integration/unicode/package.json
tests/integration/unicode/run-tests.js
tests/integration/unicode/sde.config.js
tests/integration/unicode/unicode.mdl

Fixes #532 
@ToddFincannonEI: This is the companion to the antlr4-vensim PR https://github.com/climateinteractive/antlr4-vensim/pull/14 that I just filed.
This one updates SDE to use the gitpkg (pre-release) version of antlr4-vensim containing the fix and adds an integration test to verify that it no longer chokes on non-Latin characters in variable names.
Once you approve these PRs, I'll publish antlr4-vensim and will update this one before merge to use the latest published version instead of the gitpkg version.

fix: update to latest antlr4-vensim with support for Unicode characters in variable names

---

examples/house-game/packages/app/vite.config.js
examples/sample-check-app/package.json
examples/sample-check-app/src/env.d.ts
examples/sample-check-app/src/index.ts
examples/sample-check-bundle/src/bundle.ts
examples/sample-check-bundle/src/env.d.ts
examples/sample-check-tests/src/comparisons/comparison-specs.ts
examples/sample-check-tests/src/comparisons/comparisons.yaml
packages/check-core/schema/comparison.schema.json
packages/check-core/src/comparison/_shared/_mocks/mock-resolved-types.ts
packages/check-core/src/comparison/_shared/comparison-resolved-types.ts
packages/check-core/src/comparison/config/_mocks/mock-spec-types.ts
packages/check-core/src/comparison/config/comparison-config.ts
packages/check-core/src/comparison/config/comparison-spec-types.ts
packages/check-core/src/comparison/config/parse/comparison-parser.spec.ts
packages/check-core/src/comparison/config/parse/comparison-parser.ts
packages/check-core/src/comparison/config/parse/comparison.schema.js
packages/check-core/src/comparison/config/resolve/comparison-resolver.spec.ts
packages/check-core/src/comparison/config/resolve/comparison-resolver.ts
packages/check-core/src/config/config.ts
packages/check-ui-shell/src/components/compare/detail/compare-detail-vm.ts
packages/check-ui-shell/src/components/compare/summary/comparison-summary-vm.ts
packages/check-ui-shell/src/components/summary/summary-vm.ts

Fixes #539 
This updates the model-check packages to allow for more control over which graphs are displayed in a comparison view and in which order.  See issue for more details.

feat: add support for configuring comparison graph groups and order

---

packages/check-core/src/comparison/config/comparison-config.ts
packages/check-core/src/comparison/config/comparison-datasets.ts
packages/check-ui-shell/src/components/compare/detail/compare-detail-row-vm.ts

Fixes #540 
This adds a new optional method to allow for overriding the default logic for choosing which context graphs are displayed below a box in model-check.  See issue for more details.

feat: allow for customizing the set of context graphs that are displayed for a given dataset/scenario

---

packages/check-ui-shell/src/_shared/user-prefs.ts
packages/check-ui-shell/src/app-vm.ts
packages/check-ui-shell/src/components/compare/detail/compare-detail-box-vm.ts
packages/check-ui-shell/src/components/compare/detail/compare-detail-row-vm.ts
packages/check-ui-shell/src/components/compare/detail/compare-detail-vm.ts
packages/check-ui-shell/src/components/graphs/comparison-graph-view.ts
packages/check-ui-shell/src/components/graphs/comparison-graph-vm.ts
packages/check-ui-shell/src/components/graphs/comparison-graph.svelte
packages/check-ui-shell/src/components/header/header-vm.ts
packages/check-ui-shell/src/components/header/header.svelte

Fixes #547 
This improves model-check with a new view option to show all graphs in a row with a consistent y-axis for easier (visual) comparison.  See issue for more details.

feat: add view option for consistent y-axis limits across a row of comparison graphs

---

examples/sample-check-tests/src/index.ts
packages/check-core/src/comparison/config/comparison-config.ts
packages/check-core/src/comparison/config/comparison-datasets.ts
packages/check-core/src/index.ts
packages/check-ui-shell/src/components/check/summary/check-summary-graph-box-vm.ts
packages/check-ui-shell/src/components/compare/detail/compare-detail-box-vm.ts
packages/check-ui-shell/src/components/graphs/comparison-graph-view.ts
packages/check-ui-shell/src/components/graphs/comparison-graph-vm.ts

Fixes #549 
This improves model-check by adding the ability to include extra reference plots in a comparison graph.  See issue for more details.

feat: allow for adding reference plots to a comparison graph

---

examples/sample-check-tests/src/comparisons/comparisons.yaml
packages/check-core/schema/comparison.schema.json
packages/check-core/src/comparison/_shared/_mocks/mock-resolved-types.ts
packages/check-core/src/comparison/_shared/comparison-resolved-types.ts
packages/check-core/src/comparison/config/_mocks/mock-spec-types.ts
packages/check-core/src/comparison/config/comparison-datasets.ts
packages/check-core/src/comparison/config/comparison-spec-types.ts
packages/check-core/src/comparison/config/parse/comparison-parser.spec.ts
packages/check-core/src/comparison/config/parse/comparison-parser.ts
packages/check-core/src/comparison/config/parse/comparison.schema.js
packages/check-core/src/comparison/config/resolve/comparison-resolver.spec.ts
packages/check-core/src/comparison/config/resolve/comparison-resolver.ts
packages/check-core/src/comparison/report/comparison-group-scores.ts
packages/check-core/src/comparison/report/comparison-group-types.ts
packages/check-core/src/comparison/report/comparison-grouping.ts
packages/check-core/src/index.ts
packages/check-ui-shell/src/app-vm.ts
packages/check-ui-shell/src/components/_shared/lazy.svelte
packages/check-ui-shell/src/components/compare/_shared/pinned-item-state.ts
packages/check-ui-shell/src/components/compare/detail/compare-detail-box-vm.ts
packages/check-ui-shell/src/components/compare/detail/compare-detail-box.svelte
packages/check-ui-shell/src/components/compare/detail/compare-detail-row-vm.ts
packages/check-ui-shell/src/components/compare/detail/compare-detail-vm.ts
packages/check-ui-shell/src/components/compare/detail/compare-detail.svelte
packages/check-ui-shell/src/components/compare/detail/compare-graphs-row-vm.ts
packages/check-ui-shell/src/components/compare/summary/comparison-summary-row-vm.ts
packages/check-ui-shell/src/components/compare/summary/comparison-summary-vm.ts
packages/check-ui-shell/src/components/summary/summary-vm.ts

Fixes #552 
This adds support for "free-form" comparison views that contain arbitrary rows that can have a mix of different dataset and scenario combinations.  No impact on existing model-check configurations.  See issue for more details.

feat: allow for showing a mix of dataset/scenario combinations in a single comparison view

---

packages/check-ui-shell/src/components/compare/summary/comparison-summary-vm.ts

Fixes #554 
This is a bug fix to correct a regression in check-ui-shell in the most recently published version 0.2.6, see issue for more details.

fix: correct the calculation of the number of rows with differences for a summary tab

---

packages/create/package.json
packages/create/src/index.ts
packages/create/src/step-emsdk.ts
pnpm-lock.yaml

Fixes #335 
These are simple changes to the `create` package script that streamline the process (and avoid confusion) in the case where there are pre-existing directories, like when using the `sir` example model.

fix: skip questions in create script if config and/or emsdk directories exist

---

README.md
examples/sir/README.md

Fixes #564
Improves the documentation related to discussion #559.
Edited by Chris to retroactively reference a new issue describing the changes.

docs: improve "Quick Start" documentation in top-level and sir example READMEs

---

packages/cli/src/sde-build.js
packages/cli/src/sde-test.js

Fixes #579 
Simple change to the error handlers for `sde build` and `sde test` to match the error handlers in the other `sde` commands.

fix: show full stack trace when build or test command fails

---

packages/compile/package.json
packages/compile/src/_tests/test-support.ts
packages/compile/src/model/read-equations.spec.ts
packages/compile/src/model/read-subscripts.spec.ts
packages/compile/src/model/read-variables.spec.ts

Fixes #583 
This updates the unit tests to no longer use the `sort` flag so that they compare against the definitions in the order that they appear in the source model.  No change in the default behavior of the compiler.

test: update unit tests to compare to original order of definitions

---

models/comments/expected.mdl
models/preprocess/expected.mdl
packages/cli/src/sde-generate.js
packages/compile/src/parse-and-generate.js
packages/parse/src/vensim/parse-vensim-model.ts

Fixes #586 
This restores the alphabetical sorting that we had before for the `sde generate --preprocess` command.  The default/implicit use of the preprocessor prior to parsing is unaffected.

fix: restore alphabetical sorting for `sde generate --preprocess` command

---

packages/cli/src/c/vensim.c
packages/cli/src/c/vensim.h
packages/compile/src/generate/gen-code-c.js
packages/compile/src/generate/gen-code-c.spec.ts
packages/compile/src/generate/gen-code-js.js
packages/compile/src/generate/gen-code-js.spec.ts
packages/compile/src/generate/gen-equation.js
packages/compile/src/generate/gen-lookup-from-points.js
packages/runtime/docs/functions/createLookupDef.md
packages/runtime/docs/interfaces/LookupDef.md
packages/runtime/src/_shared/lookup-def.ts
packages/runtime/src/_shared/var-indices.spec.ts
packages/runtime/src/_shared/var-indices.ts
packages/runtime/src/js-model/_mocks/mock-js-model.ts
packages/runtime/src/js-model/js-model-functions.spec.ts
packages/runtime/src/js-model/js-model-lookup.spec.ts
packages/runtime/src/js-model/js-model-lookup.ts
packages/runtime/src/js-model/js-model.ts
packages/runtime/src/wasm-model/wasm-model.ts
tests/integration/override-lookups/run-tests.js

Fixes #592 
See issue for more details.  The new behavior is well covered by tests, and I think the changes are low risk (in an area that is not yet used in many projects), so I will merge this as is and we can see later if it meets the needs of EPS.
/cc @ToddFincannonEI

fix: allow for resetting a lookup at runtime back to its original data

---

packages/cli/src/c/main.c
packages/cli/src/c/makefile

Fixes #595
See issue #595 for details.

fix: increase C input buffer size + change default optimization flag for C compilation to `-O2`

---

models/separateall/separateall.dat
models/separateall/separateall.mdl
models/separateall/separateall_check.sh
models/separateall/separateall_spec.json
packages/compile/src/model/model.js
packages/compile/src/model/read-equations.js
packages/compile/src/model/read-equations.spec.ts
packages/compile/src/model/read-variables.js

Fixes #601 
This PR proposes an alternative to the `specialSeparationDims` syntax to avoid having to maintain the list in cases where all variables containing a given subscript should be separated.
The spec file can now contain a property named `separateAllVarsWithDims` with an array value. Each entry is either a dimension name string in canonical format, or an array of dimension names.
If a variable LHS matches all dimension names in one of the `separateAllVarsWithDims` entries, then it is separated on those dimensions. If a variable is specifically called out in   `specialSeparationDims`, then that takes precedence, and `separateAllVarsWithDims` is not checked. It does not make sense for a variable separation to be listed in both formats.
I added a test model called `separateall.mdl` …

feat: add `separateAllVarsWithDims` option to spec file to separate all vars with a dimension on the LHS

---

packages/create/src/step-mdl.ts

Fixes #605 
This corrects an issue with the `@sdeverywhere/create` package that caused it to set invalid paths in the generated config file on Windows.  See issue for details.

fix: convert paths to use POSIX separators when detecting mdl files

---

packages/create/.gitignore
packages/create/package.json
packages/create/src/step-config.ts
packages/create/tests/step-config.spec.ts
packages/create/tests/step-directory.spec.ts
pnpm-lock.yaml

Fixes #357 
This is a low-risk change that updates the `@sdeverywhere/create` package to read from the generated JSON file instead of the generated YAML file.  I've also included a new integration test that verifies the behavior of the step that reads the JSON file and generates config files.  More details in the issue.

fix: read from json model listing instead of yaml file + remove yaml dependency in create package
