climateinteractive/SDEverywhere

src/c/makefile
Solve issue with running generated by SDEverywhere modes on Linux environment.
-----
Ivan from sdCloud.io
=> Added ability to build models in Linux environment

src/CodeGen.js, src/EquationGen.js, src/c/sde.h, src/c/vensim.c, src/c/vensim.h
See #18 for more information and performance numbers.
Fixes #18
=> perf: use static arrays for holding lookup data

src/CodeGen.js
See #19 for more information and performance numbers.
Fixes #19
=> perf: break large functions into chunked sub-functions

src/EquationGen.js, src/Subscript.js
More details in #23.
Fixes #23
=> perf: replace dimension array access with simple index

src/sde-build.js, src/sde-run.js, src/sde-test.js
=> fix: add async and await to some chained cli functions

src/Preprocessor.js
=> feat: sort equations alphabetically when preprocessing mdl file

models/prune/prune.mdl, models/prune/prune_check.sh, models/prune/prune_spec.json, src/Model.js
=> fix: record variants of a subscripted variable in removeUnusedVariables

src/EquationGen.js
=> fix: abort code generation on finding a lookup of size zero

.eslintrc-js-common.cjs, .vscode/settings.json, package.json, packages/cli/.eslintrc.cjs, packages/cli/package.json, packages/cli/src/sde-which.js, packages/compile/.eslintrc.cjs, packages/compile/package.json, packages/compile/src/_shared/helpers.js, packages/compile/src/_shared/subscript.js, packages/compile/src/generate/equation-gen.js, packages/compile/src/model/equation-reader.js, packages/compile/src/model/model.js, packages/compile/src/preprocess/preprocessor.js, pnpm-lock.yaml
=> build: add eslint and fix flagged issues

packages/plugin-check/package.json, packages/plugin-worker/package.json, pnpm-lock.yaml
=> fix: add rollup as dependency to avoid issues with transitive peerDependencies

packages/check-ui-shell/package.json, pnpm-lock.yaml
=> fix: move svelte-awesome to devDependencies to avoid peer dependency issues

packages/build/src/build/impl/watch.ts
=> fix: log build errors in development mode

examples/hello-world/package.json, examples/template-default/package.json, examples/template-minimal/package.json, packages/plugin-check/package.json, packages/plugin-config/package.json, packages/plugin-vite/package.json, packages/plugin-wasm/package.json, packages/plugin-worker/package.json, pnpm-lock.yaml
=> fix: make build package a peer dependency for plugins

examples/sample-check-app/package.json, examples/sample-check-bundle/package.json, examples/sample-check-tests/package.json, examples/template-default/packages/app/package.json, package.json, packages/check-ui-shell/package.json, packages/plugin-check/package.json, packages/plugin-check/src/vite-config-for-report.ts, packages/plugin-check/src/vite-config-for-tests.ts, packages/plugin-check/template-report/tsconfig.json, packages/plugin-check/template-tests/src/index.ts, packages/plugin-check/template-tests/tsconfig.json, packages/plugin-vite/package.json, packages/plugin-worker/package.json, pnpm-lock.yaml
=> fix: upgrade to vite 3.1.3

.github/workflows/build.yaml, scripts/ci-test-e2e
Fixes #243 
See issue for the before/after build time stats.
=> build: run model tests in a separate job

packages/create/src/step-deps.ts
=> fix: only report error for install deps step if exit code is non-zero

examples/template-default/packages/app/src/index.js
=> fix: preserve selected graph across page reloads in app template

examples/template-default/.gitignore, examples/template-default/packages/core/package.json, examples/template-minimal/.gitignore
=> fix: add vite to devDependencies for template-default core package

examples/template-default/packages/app/src/index.css, examples/template-default/packages/app/src/index.js
Fixes #11 
This adds a default value tick to each slider in the default app template, as requested by Travis Franck.
=> fix: include tick for slider default in template-default

packages/build/docs/index.md
=> docs: remove references to obsolete properties in build package API docs

README.md
=> docs: update README intro + link to "Supported Vensim Functions" wiki page

packages/parse/src/ast/reduce-expr.spec.ts, packages/parse/src/ast/reduce-expr.ts
Fixes #414
Details in the issue.  Test case included.
=> fix: implement unary NOT case for reduceExpr

packages/compile/src/model/model.js
Fixes #442
I refactored the tail-recursive recordRefsOfVariable function as an iterative function with an auxiliary stack. Details in #442.
=> fix: rewrite recordRefsOfVariable to avoid blowing the stack

examples/house-game/packages/app/tsconfig.json, examples/sample-check-app/package.json, examples/sample-check-app/tsconfig-base.json, examples/sample-check-app/tsconfig-build.json, examples/sample-check-bundle/package.json, examples/sample-check-tests/package.json, examples/sample-check-tests/tsconfig-base.json, examples/sample-check-tests/tsconfig-build.json, packages/build/package.json, packages/check-ui-shell/package.json, packages/create/package.json, packages/plugin-check/package.json, packages/plugin-config/package.json, packages/plugin-config/src/processor.spec.ts, packages/plugin-vite/package.json, packages/plugin-wasm/package.json, packages/plugin-worker/package.json, packages/runtime-async/package.json
=> build: include test files when running type-check scripts

packages/compile/src/model/read-equation-fn-delay.js, packages/compile/src/model/read-equation-fn-game.js, packages/compile/src/model/read-equation-fn-npv.js, packages/compile/src/model/read-equation-fn-smooth.js, packages/compile/src/model/read-equation-fn-trend.js, packages/compile/src/model/read-equation-fn-with-lookup.js, packages/compile/src/model/read-equations.js
Fixes #566 
See issue for more details.  There is no impact on existing behavior and all tests are passing.
=> refactor: add generated variables in bulk before calling readEquations

packages/compile/src/generate/gen-code-c.spec.ts, packages/compile/src/generate/gen-code-js.spec.ts, packages/compile/src/model/toposort.js
Fixes #599 
@ToddFincannonEI: I included your fix and updated the tests accordingly.  It's a low-risk change so I will merge without awaiting review.
=> fix: add arrow that was missing in cyclic dependency error message

packages/cli/src/sde-bundle.js, pnpm-lock.yaml, scripts/ci-run-js-int-tests, tests/integration/bundle-exit-code/bundle-exit-code.mdl, tests/integration/bundle-exit-code/checks/checks.yaml, tests/integration/bundle-exit-code/package.json, tests/integration/bundle-exit-code/run-tests.sh, tests/integration/bundle-exit-code/sde.config.js
Fixes #617
See issue for details.  I added an integration test to verify that it now works according to expectation.
=> fix: correct the exit code reported by the `sde bundle` command

examples/house-game/packages/app/index.html, examples/house-game/packages/app/src/components/graph/graph-view.ts, examples/house-game/packages/app/src/model/app-model.ts, examples/sample-check-app/index.html, examples/template-default/package.json, examples/template-default/packages/app/index.html, examples/template-default/packages/app/src/graph-view.ts, examples/template-svelte/package.json, examples/template-svelte/packages/app/package.json, package.json, packages/check-core/src/comparison/config/resolve/comparison-resolver.ts, packages/check-core/src/comparison/run/comparison-data-coordinator.ts, packages/check-core/src/suite/suite-runner.ts, packages/check-ui-shell/src/app-vm.ts, packages/check-ui-shell/src/components/_shared/selector-vm.ts, packages/check-ui-shell/src/components/graphs/comparison-graph-view.ts, packages/check-ui-shell/src/components/perf/perf-vm.ts, packages/check-ui-shell/src/components/playground/list-item-vm.ts, packages/check-ui-shell/src/components/playground/sel-list-vm.ts, packages/check-ui-shell/src/components/summary/tab-bar-vm.ts, packages/plugin-check/template-report/index.html, packages/runtime/src/_shared/outputs.ts, packages/runtime/src/model-scheduler/multi-context-model-scheduler.ts, pnpm-lock.yaml
Fixes #652 
See issue for details.  The only changes in the code are trivial formatting changes made by the upgraded Prettier.
=> build: upgrade prettier to 3.6.2
